backend:
  name: git-gateway
  branch: creare-site-ahsfy
  identity_url: https://ahsfymagazin.netlify.app/.netlify/identity
  gateway_url: https://ahsfymagazin.netlify.app/.netlify/git

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://ahsfymagazin.netlify.app
display_url: https://ahsfymagazin.netlify.app

collections:
  - name: "produse"
    label: "Produse"
    folder: "content/produse"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titlu", name: "title", widget: "string" }
      - { label: "Descriere", name: "description", widget: "text" }
      - { label: "Preț", name: "price", widget: "number" }
      - { label: "Imagine", name: "image", widget: "image" }

